env:
  INTERPRETERS: '!hbase,!jdbc,!file,!flink,!cassandra,!elasticsearch,!bigquery,!alluxio,!livy,!groovy,!java,!neo4j,!sparql,!mongodb'
  MAVEN_ARGS: -B --no-transfer-progress
  MAVEN_OPTS: -Xms1024M -Xmx2048M -XX:MaxMetaspaceSize=1024m -XX:-UseGCOverheadLimit
    -Dhttp.keepAlive=false -Dmaven.wagon.http.pool=false -Dmaven.wagon.http.retryHandler.count=3
  SPARK_LOCAL_IP: 127.0.0.1
  SPARK_PRINT_LAUNCH_COMMAND: 'true'
  ZEPPELIN_HELIUM_REGISTRY: helium
  ZEPPELIN_LOCAL_IP: 127.0.0.1
jobs:
  run-e2e-tests-in-zeppelin-web:
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      name: Checkout
      uses: actions/checkout@v4
    - continue-on-error: true
      name: Tune Runner VM
      uses: ./.github/actions/tune-runner-vm
    - continue-on-error: true
      name: Set up JDK 11
      uses: actions/setup-java@v4
      with:
        distribution: temurin
        java-version: 11
    - continue-on-error: true
      name: Cache local Maven repository
      uses: actions/cache@v4
      with:
        key: ${{ runner.os }}-zeppelin-${{ hashFiles('**/pom.xml') }}
        path: '~/.m2/repository

          !~/.m2/repository/org/apache/zeppelin/

          ~/.spark-dist

          ~/.cache

          '
        restore-keys: '${{ runner.os }}-zeppelin-

          '
    - continue-on-error: true
      name: Install application
      run: ./mvnw clean install -DskipTests -am -pl zeppelin-web -Pspark-scala-2.12
        -Pspark-3.4 -Phadoop3 -Pweb-dist ${MAVEN_ARGS}
    - continue-on-error: true
      name: Run headless test
      run: xvfb-run --auto-servernum --server-args="-screen 0 1024x768x24" ./mvnw
        verify -pl zeppelin-web -Pspark-scala-2.12 -Pspark-3.4 -Phadoop3 -Pweb-dist
        -Pweb-e2e ${MAVEN_ARGS}
    - continue-on-error: true
      if: always()
      name: Print zeppelin logs
      run: if [ -d "logs" ]; then cat logs/*; fi
  run-tests-in-zeppelin-web-angular:
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      name: Checkout
      uses: actions/checkout@v4
    - continue-on-error: true
      name: Tune Runner VM
      uses: ./.github/actions/tune-runner-vm
    - continue-on-error: true
      name: Set up JDK 11
      uses: actions/setup-java@v4
      with:
        distribution: temurin
        java-version: 11
    - continue-on-error: true
      name: Cache local Maven repository
      uses: actions/cache@v4
      with:
        key: ${{ runner.os }}-zeppelin-${{ hashFiles('**/pom.xml') }}
        path: '~/.m2/repository

          !~/.m2/repository/org/apache/zeppelin/

          ~/.spark-dist

          ~/.cache

          '
        restore-keys: '${{ runner.os }}-zeppelin-

          '
    - continue-on-error: true
      name: Run headless test
      run: xvfb-run --auto-servernum --server-args="-screen 0 1024x768x24" ./mvnw
        package -pl zeppelin-web-angular -Pweb-angular ${MAVEN_ARGS}
  test-selenium-with-spark-module-for-spark-3-4:
    defaults:
      run:
        shell: bash -l {0}
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      name: Checkout
      uses: actions/checkout@v4
    - continue-on-error: true
      name: Tune Runner VM
      uses: ./.github/actions/tune-runner-vm
    - continue-on-error: true
      name: Set up JDK 11
      uses: actions/setup-java@v4
      with:
        distribution: temurin
        java-version: 11
    - continue-on-error: true
      name: Cache local Maven repository
      uses: actions/cache@v4
      with:
        key: ${{ runner.os }}-zeppelin-${{ hashFiles('**/pom.xml') }}
        path: '~/.m2/repository

          !~/.m2/repository/org/apache/zeppelin/

          ~/.spark-dist

          ~/.cache

          '
        restore-keys: '${{ runner.os }}-zeppelin-

          '
    - continue-on-error: true
      name: Setup conda environment with python 3.9 and R
      uses: conda-incubator/setup-miniconda@v3
      with:
        activate-environment: python_3_with_R
        auto-activate-base: false
        channel-priority: true
        channels: conda-forge,defaults
        environment-file: testing/env_python_3_with_R.yml
        miniforge-variant: Mambaforge
        python-version: 3.9
        use-mamba: true
    - continue-on-error: true
      name: Make IRkernel available to Jupyter
      run: 'R -e "IRkernel::installspec()"

        '
    - continue-on-error: true
      name: Install Environment
      run: './mvnw clean install -DskipTests -am -pl zeppelin-integration -Pintegration
        -Pspark-scala-2.12 -Pspark-3.4 -Phadoop3 -Pweb-dist ${MAVEN_ARGS}

        '
    - continue-on-error: true
      name: run tests
      run: 'xvfb-run --auto-servernum --server-args="-screen 0 1600x1024x16" ./mvnw
        verify -DfailIfNoTests=false -pl zeppelin-integration -Pintegration -Pspark-scala-2.12
        -Pspark-3.4 -Phadoop3 -Pweb-dist -Pusing-source-tree ${MAVEN_ARGS}

        '
    - continue-on-error: true
      if: always()
      name: Print zeppelin logs
      run: if [ -d "logs" ]; then cat logs/*; fi
name: frontend
on:
  repository_dispatch:
    types: trigger-ga___frontend.yml
permissions:
  contents: read
